### ISSUE TITLE
Using {{customVariables}} with oneOf schema objects throw an Exception: violated Too many elements

### ISSUE THREAD

**Issue by limonadev** [peiffer-innovations/json_dynamic_widget#12]
## Steps to reproduce
1. Register some custom variable (`EdgeInsetsGeometry` or `BorderRadius`) in the Registry.
2. Use that variable in any json

## JSON example
```json
{
  "type": "scaffold",
  "args": {
    "appBar": {
      "type": "app_bar",
      "args": {
        "title": {
          "type": "text",
          "args": {
            "text": "Example"
          }
        }
      }
    },
    "body": {
      "type": "set_value",
      "args": {
        "customPadding": 16
      },
      "child": {
        "type": "flat_button",
        "args": {
          "padding": "{{customPadding}}"
        },
        "child": {
          "type": "text",
          "args": {
            "text": "Random Text"
          }
        }
      }
    }
  }
}
```

For what I was checking, this error happens when the Schema of the objects uses `SchemaHelper.objectSchema(id)` and the schema referenced by that `id` uses `oneOf` and one of the options is `'string'`.

**Comment by limonadev** [comment]
This also happens if insted of `"{{customPadding}}"` the property receive a random string.

**Comment by jpeiffer** [comment]
Issue confirmed, investigating...

**Comment by jpeiffer** [comment]
I think I may have to abort on the schemas.  I don't want to, but the library I'm depending on hasn't been maintained in over a year and there's no good reason this shouldn't have validated because when it his the schema it is a string; which doesn't make sense to fail out with a "too many elements" error since that error is _supposed_ to be for when you have an object with elements that don't exist in the object definition.

**Comment by jpeiffer** [comment]
Phew, nope.  Found the issue.

It's going to take some more effort, but the problem is that the EdgeInsetsPadding allowed a string value _and_ the objectSchema did too.  Removing one of those allowed it to validate.

There's some other objects that fall under this same setup so I need to trace those out to make sure this is properly fixed.

Seriously, congrats and thanks for finding this because "padding" is one of an exceptionally small few values that would trigger this particular issue.  Radius is the other I can think of off the top of my head.

**Comment by jpeiffer** [comment]
Fix checked in to `json_theme` and applied to here as well.

I added your example to prove the fix, but because of how unique and strange this particular issue ended up being, I would like to ask you please retest and close if you feel this is resolved.

**Comment by limonadev** [comment]
I retested it, everything works fine now!
