### ISSUE TITLE
Not able to create Text widget from json  inside the custom widget 

### ISSUE THREAD

**Issue by harsh896213** [peiffer-innovations/json_dynamic_widget#143]
{
             "type": "custom_tile",
             "args": {
               "leading": {
                 "type": "icon",
                 "args": {
                   "icon": {
                     "codePoint": 57369,
                     "fontFamily": "MaterialIcons"
                   },
                   "size": 70
                 }
               },
               "title": {
                 "type": "text",
                 "args": {
                   "text": "Heart Shaker",
                   "style": {
                     "color": "#fff"
                   }
                 }
               },
               "subtitle": {
                 "type": "text",
                 "args": {
                   "text": "TWICE",
                   "style": {
                     "color": "#fff"
                   }
                 }
               }
             }
           }

**Comment by harsh896213** [comment]
@jpeiffer @crisperit

**Comment by jpeiffer** [comment]
Without seeing the code of `custom_tile` there's not much I can do.  However, you may want to look at the implementation of [list_tile](https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/lib/src/builders/json_list_tile_builder.dart) as it also has a `leading`, `title`, and `subtitle`.  Specifically the [card.json](https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/example/assets/pages/card.json) example works and shows a `list_tile` with a leading, title, and subtitle working.

**Comment by jpeiffer** [comment]
I also see you're using a code point in the icon.  You may want to consider using the [json_dynamic_widget_plugin_material_icons](https://github.com/peiffer-innovations/json_dynamic_widget_plugin_material_icons) plugin.

I found out the hard way the code points change across Flutter releases, and that's why I built that plugin.  It creates stable names that you can use to reference and the code point will follow whatever it becomes in the latest stable Flutter version.
