### ISSUE TITLE
Showing large lists without lagging

### ISSUE THREAD

**Issue by Plaltair** [peiffer-innovations/json_dynamic_widget#184]
I have two screens: A and B.

When I change from screen A to screen B, I have to pass a large list as an argument, that I will show with list_view and for_each, in this way:

`{
  "type": "list_view",
  "children": "${for_each(list, 'template')}"
}`

The problem is that there is a very noticeable lag during the screen changing.
Is there a better way to show large lists and not lag?

**Comment by jpeiffer** [comment]
In order to help meaningfully, I'd need an example that shows the lag.

One note though, the schema validation is slow.  It's enabled in debug because it gives really helpful error messages but there is a performance cost to that help.

It's disabled by default in profile and release mode, but you can disable it in debug mode by calling `SchemaValidator.enabled = false`.

**Comment by naveen715** [comment]
> I have two screens: A and B.
> 
> When I change from screen A to screen B, I have to pass a large list as an argument, that I will show with list_view and for_each, in this way:
> 
> `{ "type": "list_view", "children": "${for_each(list, 'template')}" }`
> 
> The problem is that there is a very noticeable lag during the screen changing. Is there a better way to show large lists and not lag?

Please provide the code for list and template how are you creating it and using it
