### ISSUE TITLE
Export a widget as json data, for rebuilding dynamic widget from the file

### ISSUE THREAD

**Issue by piyushdevganiya** [peiffer-innovations/json_dynamic_widget#189]
Would it be possible, if we are able to export a widget to json data. Later we can import the json data and generate widget from it.

This way, we can speed up building the json data.

**Comment by crisperit** [comment]
We're slowly working on "encoders"

https://github.com/peiffer-innovations/json_dynamic_widget/pull/170/files#diff-903842f7dce91921bf6dd66d2f56b6f09b634695cfc511a2dc7af0432fa0cd7e

**Comment by jpeiffer** [comment]
Take a look at the [pre-release version and it's documentation](https://pub.dev/packages/json_dynamic_widget/versions/7.0.0-dev6).  That is getting close to becoming live and supports reverse encoding to take the dart code into JSON / YAML.

I'm going to close this issue because the functionality exists now.  If you have any problems with the pre-release (or if you use it post-release) v7 then please open it as a net new issue.

**Comment by piyushdevganiya** [comment]
Thank you for the update regarding the pre-release version and its new
features. I'm excited to see the reverse encoding functionality being
introduced.

Could you please provide some information regarding when the v7 release is
expected to become official? Having an estimated release date would be
immensely helpful for planning purposes on our project.
