### ISSUE TITLE
v7 and breaking changes

### ISSUE THREAD

**Issue by xalikoutis** [peiffer-innovations/json_dynamic_widget#207]
Hi,
First of all congrats for the great package.
Reading the v7 changelog saw that `Both child and children have moved into the args for all widgets.`
That is an ultimate stopper for us as we have lots and lots custom json templates stored in our backend.
Is it something you can consider not doing it?

Thanks

**Comment by jpeiffer** [comment]
Unfortunately, to meet the goals of the 7.0.0 release they need to move because they aren't technically special.  When all widgets were "built by humans" we could make the distinction regarding where those attributes go.  But once they are built by a code generator, the code generator just looks at all the attributes and groups them.  It doesn't make sense to try to move some to the `args` but not others, and the problem gets worse when longer term maintainability is considered.

Having child and children outside the `args` had other unfortunate impacts.  For example "builder".  Should that be outside or inside the "args"?  It's "people-y" the same as child / children.  Issues like the "body" on a Scaffold (rather than it being a "child") also led to some awkward compromises.  That led to the decision that if it's an attribute of the widget, it goes to "args" and if it's an attribute to the framework (`type`, `id`, `listen`, etc) it can live outside.

A few notes of mitigation...
1. The next release is a major release with announced breaking changes.  You have an option to not upgrading and sticking with 6.0.0.  Assuming your pubspec.yaml uses the standard `^6.0.0` (or whatever) 
2. Realizing that this was a big deal, the 7.0.0 branch also includes a migration script that can automatically migrate existing JSON templates to the new structure for all known breaking changes.  You can apply that same script to your custom templates.  That script was what was used to migrate all the example templates.

**Comment by xalikoutis** [comment]
Thanks @jpeiffer for your answer probably will stick with v6
