### ISSUE TITLE
onTap pada ListTile

### ISSUE THREAD

**Issue by achunk17** [peiffer-innovations/json_dynamic_widget#343]
Kenapa onTap pada ListTile dipanggil sebelum user melakukan tap/klik?

**Comment by jpeiffer** [comment]
> Why is onTap on ListTile called before the user taps/clicks?

What is passed to it needs to be a closure.  If you pass it a function, it will execute the function immediately.  This is the same as how it works with regular hard coded widgets.

Let's take the example:

```dart
void onTap() {
  print('tapped!')
}

Widget build(context) => InkWell(onTap: onTap(), child: Text('Button');
```

The moment that renders, the phrase `tapped!` will be printed because what was given was a function that immediately executes.  When using this package, it is the same.  If you pass a function immediately, it will execute the function.  In regular Dart, the answer is to use a tear off or a lambda like:

```dart
// tear off
Widget build(context) => InkWell(onTap: onTap, child: Text('Button');

// lambda
Widget build(context) => InkWell(onTap: () => onTap(), child: Text('Button');
```

Tear offs aren't possible via the registry.  So you must use a lambda.  Like....

```dart
void onTap() {
  print('tapped!')
}

void initState() {
  registry.registerFunction('tap', () => onTap());
}
```

Then in your JSON you can use:
```json
{
  "type": "ink_well",
  "args" {
    "onTap": "${tap}",
    "child": { ... }
}
```
