### ISSUE TITLE
Adding more ways of passing data via JSON format

### ISSUE THREAD

**Issue by crisperit** [peiffer-innovations/json_dynamic_widget#37]
### Current state

In the current state we have a few ways of defining values in JSON format:

* `"key":"Some text"`
* `"key": "{{dynamic_var}}"`
* `"key": "!{{static_var}}"`
* `"on_click": "##fun(a,b)##"`
* `"map": {"key": "value"}` 

### Proposed enhancements

* Pass maps in the function
For now we are only able to pass simple values in function call like: `"##fun(a,b)##"`
To pass more complicated values in the function call we have to use the variables. For example `##dynamic(addActionVar)##`

It requires a lot of jumping and additional nesting often just to make a function call. That's why we can provide such a support for a maps in a function calls.

`##dynamic({type : add, builder : items, values:{}}, otherValue)##`

* Pass functions the function
Similar we can provide a support to a nested function calls:
``"##fun(##fun2()##, ##fun3()##)##"`` 

* Make more complicated strings
Instead of deciding if the whole value should be variable or text or function call we can try to join them all like:

`"combinedText": "Hello ##name()##! I'm {{name}}. What is your name?"`

**Comment by jpeiffer** [comment]
You missed one in that you can pass a variable to a function, but otherwise the current state is pretty accurate.

The current function syntax was chosen to be easy to parse and not require a lot of enhanced escape control characters.  Rather than bolting on to the current syntax, I'd prefer to harmonize on the mustache-like syntax as a new lexicon for functions.  Something like: `Hello ${{name()}}! ...`

I think that's more familiar for folks than the current double pound.  Of course, that would also require supporting escape characters (which to be honest is probably something the variable resolver should support too).

I'm not opposed to these enhancements being added, but if they were I would very much recommend adding them with the more Dart-like following syntax:
* `${{setName("My Name")}}`
* `${{printVariable(var1)}}`
* `${{increment(counter(), 1)}}`
* `Hello ${{name()}}!  I'm {{name}}...`
* `${{useMap({"key": "value", "sub": {"key2": "value2"}})}}`

**Comment by crisperit** [comment]
Good idea :)

What I would add is that inside of JSON we have to use `'` instead of `"` - so `${{setName('My Name')}}` instead of `${{setName("My Name")}}`

And also in the map
`${{useMap({'key': 'value', 'sub': {'key2': 'value2'}})}}`

In functions you've removed {{}} brackets for variables / functions
```
${{printVariable(var1)}}
${{increment(counter(), 1)}}
```
That is nice shortcut - I'm wondering only if we wanna somehow indicate that some variable used in a function params is static or dynamic

**Comment by jpeiffer** [comment]
Using a single quote solves the problems you have until you have a "ain't" in your text (or a "he'd, a she'd, it's, etc").

And that's the larger problem scope.  If there is going to be a new dialect for parsing functions, it needs to be in a proper [BNF](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form) definition.

I am 100% ok with having it happen.  It's just, I recognize the scope and scale of the effort and cannot take it on myself.

**Comment by crisperit** [comment]
I'm happy to do it - if we will agree fully on the convention

I've proposed `'` because using `"` in json requires adding escapes

```
"onChange": "${{setName(\"My Name\")}}"
vs
"onChange": "${{setName('My Name')}}"
```

Have you used BNF definition for the previous syntax ?

**Comment by jpeiffer** [comment]
Yeah, I've used BNF a bunch of times in the past.  Once you use it a few times, it's actually pretty easy.

I guess I should have said, "I'd suggest BNF", if you know of other ways to express syntax, I'm open to them.  It's just that BNF has worked really really well for me in the past.

**Comment by crisperit** [comment]
I've noted the idea for the new syntax in a form of JSON examples:
```
{
    "text": "text",
    "textWithVar": "Hello ${name}",
    "textWithFunction": "Hello ${name()}",
    "variableDynamic": "${variable}",
    "variableStatic": "${static variable}",
    "functionEmpty": "${function()}",
    "functionTextParam": "${function('text')}",
    "functionTextParamWithApostrophe": "${function('He\\'d never do that')}",
    "functionTextParamWithComma": "${function('Hey\\, how are you?')}",
    "functionTextParams": "${function('Hey\\, how are you?','He\\'d never do that')}",
    "functionVariableParam": "${function(variable)}",
    "functionVariableParams": "${function(variable1,static variable2)}",
    "functionFunction": "${function(funParam())}",
    "functionFunctions": "${function(funParam1(),funParam2('text', variable))}",
    "functionMap": "${function({'key':'That\\'s the value'})}",
    "functionMaps": "${function({'key':'That\\'s the value 1'},{'key':'That\\'s the value 2'})}",
    "functionCombined": "${function(variable,static staticVar,'text',funParam(funParamParam()),{'key':'value'}}"
}
```

In a BNF it looks like that:
```
value ::= "${<function>}" | "${<variable>}" | "<parameterized-string>" | <json>
variable ::= <variable-name> | <modifier> <variable-name>
variable-name ::= <string>
modifier ::= static
function ::= ${<function-name>(<parameter-list>)} | ${<function-name>()}
function-name ::= <string>
parameter-list ::= <parameter> | <parameter>, <parameter-list>
parameter ::= '<string>' | <function> | <variable> | <map>
map ::= {map-entries} | {}
map-entries ::= <map-entry> | <map-entry>,<map-entries>
map-entry ::= '<key>':'${<function>}' | '<key>':'<parameterized-string>' | '<key>':'${<variable>}' | '<key>':<map>
key ::= <key>
parameterized-string ::= <parameterized-string-element> | <parameterized-string-element> <parameterized-string> | <parameterized-string><parameterized-string-element>
parameterized-string-element ::= <string> | ${<variable>} | ${function}
```

The changes description:
* I've used the same opening brackets for function and variables
* Dynamic variable instead of `{{dynamic_variable}}` now it is `${dynamic_variable}`
* Static variable instead of `!{{static_variable}}` now it is `${static static_variable}` - so I've added the modifiers to the variables - like in programming. The modifiers can grow over time if there will be more idea for that
* Strings in function params are between `'` characters. Sometimes there will be a need to escape `'` and `,` characters and this can be available like that: `'Hey Thomas\\, - that\\'s the value'`
* I've also described <map> element inside of function params

@jpeiffer What do you think about that?

**Comment by jpeiffer** [comment]
I like it.

The big difference is I want to keep the double curly's and not switch to single.  The reason is with single curlys, you cannot tell the difference between JSON and a variable absent a prefix.

So let's say you have something like this:
```
{
  "child": "set_value",
  "args": {
    "jsonEncodedVariable": "{\"foo\": \"bar\"}"
  }
```

With single curly braces it's actually impossible to know if that was meant to be JSON passed in as a string encoded JSON  or if it is a variable named `"foo": "bar"` (which may seem odd but is currently supported).  You can make an educated guess, but not know with mathematical certainty.  With double curly's, you know with certainty.

Plus, switching from double to single will 100% break backward compatibility and make for a huge migration effort for devs.  Where as if we stick with double, we can keep a backwards compatible syntax and this new function and map setup can be "net new" so all existing JSON works and people can simply add this new feature when it's ready.

**Comment by crisperit** [comment]
It is single curly brace - sure buut with dolar sign at the start `$`
So `${static var}`

Additionally it is really easy to differentiate var content from JSON. We can ban characters like `:` or `"`  from the regexp - [A-Za-z-_]+ 

Yeah - I plan to create backward compatibility and create the migration docs for sure. 
If single curly brace is possible I think that we should aim for it

Btw. I've already started the implementation - I'll let you know when it will be ready

**Comment by crisperit** [comment]
Can be closed after releasing https://github.com/peiffer-innovations/json_dynamic_widget/tree/beta
