### ISSUE TITLE
error on build in jsonicobuilder

### ISSUE THREAD

**Issue by FelipeSantos75** [peiffer-innovations/json_dynamic_widget#40]
Hi, when i try build a apk and keep getting error
in my project i commented the lines and it worked. 
in theme_decoder.dart in line 3781. 

anyway, its a amazing work. i hope one day can help

**Comment by jpeiffer** [comment]
You didn't really give me a lot to work with to try to help, but I'll give it a shot...  I think you may be getting this error:
```
This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
...
```

If so, you need to add the `--no-tree-shake-icons` flag to your build.
```
flutter build apk --release --no-tree-shake-icons
```

That's because `IconData` can be built dynamically by the project (otherwise icons wouldn't be able to be used).  When Flutter encounters an instance of `IconData` that isn't a constant, it can no longer detect what icons are vs are not used by the app and thus cannot shake them out.

The `--no-tree-shake-icons` command will increase your app size by a few hundred kilobytes.  The Flutter team is exceptionally aggressive on trying to keep app sizes down to a degree that could almost be called obsessive.  That's why they made the tree shaking option the default vs the other way around.

**Comment by jpeiffer** [comment]
I'm going to assume other devs are likely to encounter the same issue you did and added instructions to the readme.

I'm going to go ahead and close this issue.  If your problem persists, please open a new one with more details about the errors you are receiving, the versions you are referencing, etc.
