### ISSUE TITLE
Possibility to generate json from widget

### ISSUE THREAD

**Issue by KlausJokisuo** [peiffer-innovations/json_dynamic_widget#41]
It's quite time-consuming to manually create a JSON structure for the widget. Would it be possible to generate JSON from a widget?

**Comment by jpeiffer** [comment]
That's not currently on my radar, but PR's are always welcome.  :)

This may be of use:
https://github.com/peiffer-innovations/json_dynamic_widget_builder

It's still very much a WIP, but it may help with generating some of your JSON.

**Comment by lonchus** [comment]
@jpeiffer  Thanks for the investment in json_dynamic_widget, and  json_dynamic_widget_builder. I agree hand authoring the JSON is time-consuming, and I think a tool like json_dynamic_widget_builder is a part of the solution, I also see where generating a json file from any node (and its children) in the widget tree would be extremely valuable. For example, refactoring existing widgets into shared widgets for design libraries. This would likely help with adopting json_dynamic_widget into more mature codebases.

I'm considering going down this path and have invested some thought into how I would walk the widget tree to reverse lookup and generate the json serializing any non-default valued fields, if I do, I will certainly share a PR.

Another of my particular use cases is to leverage json_dynamic_widget compositionally and allow the user to select widgets (like you would in a WYSIWYG editor) that identifies where that widget is within the widget tree behind the scenes, then output the json which would recreate that branch of the widget, effectively allowing me to then copy and paste that widget into an appropriate container. This could be useful for your json_dynamic_widget_builder as well, but when building a full editor like you have, it makes sense to have metadata that facilitates the process, which isn't always available in mainstream applications.

**Comment by crisperit** [comment]
I personally am thinking that it is not possible or near impossible to achieve widget to JSON serialization. I bet that only simple views might be serializable and this might be really limited feature - so we might easily create a view that won't be serializable because of some fancy state management logic etc..

I believe that going into a builder is a right direction. We can easily drag & drop and see immediately the result. Maybe even we can support to import custom builders & functions there (so make that builder somehow generic)

I'm voting on builder instead of generator!

**Comment by ocgully** [comment]
There's a similar project to json dynamic widget which has written a widget to json exporter.

https://pub.dev/packages/dynamic_widget

> You don't need to write the json code by hand, you can export your flutter code to json code efficiently with DynamicWidgetJsonExportor widget. You just need to wrap your flutter code with DynamicWidgetJsonExportor widget, then invoke its exportJsonString() method, look at following example, click the "export" button, it will find the DynamicWidgetJsonExportor widget, and export its child to json code efficiently.

Source Code starts here: https://github.com/dengyin2000/dynamic_widget/blob/master/lib/dynamic_widget/basic/dynamic_widget_json_exportor.dart

They have customized export functions for the various types, so it's heavily manual. But by no means "Near Impossible".

Beyond that, using reflection with something like Dart's Mirrors which allows you to walk through all fields for a given type (e.g. widget) and then generate the corresponding json from those values, after pruning list of values to be persisted from known default values (to make the output cleaner), sort alphabetically and append any children, and you should be able to come up with a more complete, and less manual automated solution.

https://stackoverflow.com/questions/17021327/how-do-i-get-all-fields-for-a-class-in-dart
and official documentation: https://api.dart.dev/stable/2.17.1/dart-mirrors/dart-mirrors-library.html

**Comment by crisperit** [comment]
Yeah as I've written:

>  I bet that only simple views might be serializable and this might be really limited feature

So we are able to write it buut it will work only for stateless views - without 

> some fancy state management logic etc..

So yes if we want to write sth to convert stateless views into JSON then it is pretty possible. But any stateless widgets won't be rendered of course correctly I think

**Comment by crisperit** [comment]
If we want to only support normal stateless views (without variables/functions or any state related logic) theen I can implement that

**Comment by ocgully** [comment]
Yeah, I think stateless views would be sufficient. Much of what json_dynamic_widget does is in support of that anyway. This is also a nonopinionated approach that allows for other state management paradigms (bloc, riverpods, etc.)

**Comment by jpeiffer** [comment]
To be clear, I still don't intend to invest much (if any) time in this effort, but some notes for anyone who might be interested in taking it on and putting forth a PR.

Flutter made the explicit decision to not include the parts of the SDK that would allow for Mirrors to work.  That's part of why JSON processing is so "odd" in Flutter vs other frameworks.  For more information, you can read this thread: https://github.com/flutter/flutter/issues/1150

So any solution trying to use mirrors is automatically out.

For someone interested in walking the tree and trying to build JSON, one possible path I can think of is to use the [automated_testing_framework](https://pub.dev/packages/automated_testing_framework) to do it from a live app.  That framework has the ability to find a widget in the widget tree, expose that widget to your code, and then you can query the properties to build the JSON.  Alternatively, you can do the same using the relatively new Flutter [integration_test](https://docs.flutter.dev/cookbook/testing/integration/introduction) framework to do basically same thing from a CLI rather than from a live app.  In these scenarios you'd need a way to get the generated JSON "out of the app".  Another option I suspect would work would be a `flutter_test` based "test" could do it and export it from the host runner easily though I am significantly more familiar with the capabilities of the previous two vs `flutter_test`.

Regardless of which framework you choose to find the widget with, I think the following part is basically the same...

For every widget that would need to be able to be "encoded" to JSON, you would then need something like a `JsonWidgetEncoder` that could be registered in the registry.  The encoder would have to be manually built to know how to query the widget properties and then build the JSON from said properties.

I think that technically this might be end up being straight forward and the bigger challenge would just be the LOE to build all the encoders.  If someone is willing to take that on, prove it out, and build encoders out for all the widgets this package supports then I will commit to uplifting all the first party plugins to also be able to be as encodable as possible.
