### ISSUE TITLE
bottomNavigationBar

### ISSUE THREAD

**Issue by jaser-deli** [peiffer-innovations/json_dynamic_widget#56]
How use bottomNavigationBar IN Json

 "bottomNavigationBar" : {
            "type": "bottom_navigation_bar",
            "args": {
              "items": [
              
              ]
            }            
          }

**Comment by jpeiffer** [comment]
`BottomNavigationBar` is not currently supported.  The list of supported widgets is available here:

https://github.com/peiffer-innovations/json_dynamic_widget#built-in-widgets

I'm going to close this because it's phrased as a question.  However, if you'd like to request support for `BottomNavigationBar` please feel free to open a new issue that specifically asks for support of that widget.
