### ISSUE TITLE
mediaQuery

### ISSUE THREAD

**Issue by shashikiran918** [peiffer-innovations/json_dynamic_widget#97]
How to use mediaQuery.of(context).size.height in json dynamic widget

**Comment by jpeiffer** [comment]
Please state what you are trying to accomplish because a question like this isn't really possible to answer.  Also please provide a sample of code showing what you are trying to do, it can be pure Flutter that you are asking how to re-do in this package, is fine.

Without any of the above, my ability to assist is exceptionally limited.

**Comment by jpeiffer** [comment]
Closing due to lack of response.
